version: 2

python:
  version: 3.8
  system_packages: true
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

formats: all

build:
  apt_packages:
    - gfortran


submodules:
  include: all
